name: Build & Deploy

on:
  workflow_call:

jobs:
  build-image:
    name: Build & push additional images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate docker image metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/python-discord/pinnwand
          tags: |
              type=ref,event=tag,suffix=psql
              type=raw,value=latest-psql

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Containerfile
          target: psql
          push: true
          cache-from: type=registry,ref=ghcr.io/python-discord/pinnwand:latest-psql
          cache-to: type=inline
          tags: ${{ steps.meta.outputs.tags }}
